### ISSUE TITLE
getting this right after activating the module

### ISSUE THREAD

**Issue by VaasKahnGrim** [Dot-Rar/pterodactyl-boxbilling#2]
Unexpected token "end of template" of value "" ("end of statement block" expected) in "mod_pterodactyl_index.phtml" at line 20

**Comment by Adam123321** [comment]
Hello, I am also getting this error! Unfortunately I have a felling that the Developer of this won't respond. ;(

**Comment by Adam123321** [comment]
Ok, another quick update. Managed to get in touch of the Dev who said this is a half complete project he gave up on.

**Comment by ThePotatoPony** [comment]
will wait till a resonse while trying to fix myself then. if neither happen I'm commissioning a repair

**Comment by FreshwayYT** [comment]
Can be fixed by adding in `{% endblock %}` at the end of "mod_pterodactyl_index.phtml" located in "bb-modules/Pterodactyl/html_admin"

**Comment by xeu100** [comment]
Please check the pull requests area to see the working code! It has the repairs of what Freshway said.

**Comment by xeu100** [comment]
Use the fork I'm creating

https://github.com/xeu100/pterodactyl-boxbilling/

**Comment by DavidTEC-Development** [comment]
I cannot get it to work, can any of you?

**Comment by xeu100** [comment]
As I said, check the pull requests. Here is the link. https://github.com/antonand03/pterodactyl-boxbilling/tree/patch-1

**Comment by Dot-Rar** [comment]
Oops, forgot about this. Only the frontend is done, none of the backend is working. PRs are welcome to add support, but it's unlikely that I will in the near future. Merged that PR btw.
